### PR TITLE
#118059-MSFT Graph Connector - Remove synced item if updated session …

### PR DESCRIPTION
**Pull request by GitNedim**
PR contains fix to remove content from target if updated content is already synced but new update doesn't contain any of principals (permissions) - user(s) or user group(s).

Also, minor changes for logging to use `content` terminology to be consistent.

Tested MSFT Graph Connector to verify that content is pushed to target if contains any of principals or removed if doesn't have and already exists.

### CODE REVIEW

**Comment by hohno-panopto** [comment]
This looks reasonable. Yet, I think @stevielb's review is desired.

**Review by stevielb — COMMENTED** [review]
Seems reasonable; what about admins though? This would mean an admin with full control would not be able to find a video. Are we okay with that? Also, it's kind of funny because what happens if a video gets synced and then all of us permissions are removed?

**Review by stevielb — APPROVED** [review]
Actually I answered my own question when I looked again, it will be deleted. But it is ms teams only. I think that's okay to start, but we will see if any admins actually want that content (probably not)

**Comment by GitNedim** [comment]
> Actually I answered my own question when I looked again, it will be deleted. But it is ms teams only. I think that's okay to start, but we will see if any admins actually want that content (probably not)

@stevielb if admin (Azure AD) user exists he will be returned by Search Index API as one of principals. He doesn't need to be specifically added to session to be part of session principals. This change is related to case if admin users (Azure AD users) don't exist and none of users/groups are added to session. Probably edge case but with this fix we covered that too.

**Pull request merged**
